apiVersion: v1
kind: ConfigMap
metadata:
  name: config-volume
data:
  nginx.conf: |-
    daemon off;
    user  nginx;
    worker_processes  1;
    error_log /var/log/nginx/error.log warn;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
          listen       80;
          server_name  localhost;
          location / {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:8080/;
          }
        }
    }

